- name: Run Kubeadm
  become: yes
  shell: kubeadm init --kubernetes-version=1.16.4 --service-cidr=172.16.0.0/12 --pod-network-cidr=192.168.0.0/16 --apiserver-cert-extra-sans={{ansible_facts.fqdn}},master.k8s.aws.pipsquack.ca,{{ansible_facts.all_ipv4_addresses | join(',')}}
  args:
    creates: /etc/kubernetes/admin.conf
- name: Udpate config file server
  become: yes
  lineinfile:
    path: /etc/kubernetes/admin.conf
    regexp: '^( *)server: (https?://).*(:\d+)'
    backrefs: yes
    line: '\1server: \2{{ansible_host}}\3'
- name: Creates directory
  file:
    path: "{{ansible_facts.env.HOME}}/.kube"
    state: directory
- name: Copy kubeconfig to master .kube
  become: yes
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ansible_facts.env.HOME}}/.kube/config"
    remote_src: yes
    owner: "{{ansible_user}}"
- name: Copy kubeconfig to ansible host .kube
  become: yes
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    flat: yes
- name: Install Calico
  shell: kubectl apply -f https://docs.projectcalico.org/v3.8/manifests/calico.yaml
- name: Get Kubernets join cluster command
  shell: kubeadm token create --print-join-command
  register: join_cmd
- name: Export join command
  set_fact:
    join_cmd: "{{ join_cmd.stdout }}"