kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-ingress-controller
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
data:
  enable-opentracing: "true"
  datadog-collector-host: $HOST_IP
  http-snippet: |
    server {
      listen 18080;
      location /nginx_status {
        allow all;
        stub_status on;
      }
      location / {
        return 404;
      }
    }