controller:
  service:
    type: NodePort
    nodePorts:
      http: 30080
      https: 30443
  metrics:
    enabled: true
  extraEnvs:
    - name: HOST_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
  podAnnotations:
    ad.datadoghq.com/nginx-ingress-controller.check_names: '["nginx_ingress_controller", "nginx"]'
    ad.datadoghq.com/nginx-ingress-controller.init_configs: '[{}, {}]'
    ad.datadoghq.com/nginx-ingress-controller.instances: >-
      [
        {
          "prometheus_url": "http://%%host%%:%%port_metrics%%/metrics"
        },
        {
          "nginx_status_url": "http://%%host%%:18080/nginx_status"
        }
      ]