persistence:
  enabled: false
master:
  adminPassword: letmein
  useSecurity: false
  csrf:
    defaultCrumbIssuer:
      enabled: false
  ingress:
    enabled: true
    hostName: jenkins.k8s.aws.pipsquack.ca
  jenkinsUrl: http://jenkins.k8s.aws.pipsquack.ca:30080/
  installPlugins:
    - workflow-job
    - workflow-aggregator
    - kubernetes
    - kubernetes-cd
    - git
    - datadog
  podAnnotations:
    ad.datadoghq.com/jenkins.logs: '[{"source": "jenkins","service": "jenkins","log_processing_rules": [{"type": "multi_line","name": "log_start_with_date","pattern": "\\d{4}\\-\\d{2}\\-\\d{2} \\d{2}:\\d{2}:\\d{2}\\.\\d{3}\\+\\d{4}"}]}]'