- name: upgrade all packages
  become: yes
  package:
    name: '*'
    state: latest
- name: Set /etc/hostname
  become: yes
  lineinfile:
    regex: ".*"
    dest: /etc/hostname
    line: "{{ansible_host}}"
- name: Set hostname
  become: yes
  hostname:
    name: "{{ansible_host}}"