- name: Upgrade all packages
  become: yes
  apt:
    name: "*"
    state: latest
    update_cache: true
- name: Set hostname
  become: yes
  hostname:
    name: "{{ansible_host}}"
- name: Set /etc/hostname
  become: yes
  copy:
    content: "{{ansible_host}}"
    dest: /etc/hostname
