apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: apm-demo
  labels:
    app: apm-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apm-demo
  template:
    metadata:
      labels:
        app: apm-demo
    spec:
      containers:
      - name: apm-demo
        image: yaalexf/apm-demo
        imagePullPolicy: Always
        env:
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DD_SERVICE_NAME
            value: "happypath"
          - name: DD_LOGS_INJECTION
            value: "true"
          - name: DD_TRACE_ANALYTICS_ENABLED
            value: "true"
          - name: DD_JDBC_ANALYTICS_ENABLED
            value: "true"
          - name: DD_TRACE_GLOBAL_TAGS
            value: "env:k8s-cluster"
          - name: DD_JMXFETCH_REFRESH_BEANS_PERIOD
            value: "60"
          # - name: DD_JMXFETCH_CONFIG_DIR
          #   value: "/opt/datadog-agent/etc/conf.d"
          # - name: DD_JMXFETCH_CONFIG
          #   value: "jmx.d/conf.yaml,tomcat.d/conf.yaml"
          - name: DD_JMXFETCH_CONFIG_DIR
            value: "/opt/datadog-agent/etc/conf.d"
          - name: DD_JMXFETCH_CONFIG
            value: "tomcat.d/conf.yaml"
---
apiVersion: v1
kind: Service
metadata:
  name: apm-demo
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
  - name: https
    port: 80
    nodePort: 30080
    targetPort: 8080
  selector:
    app: apm-demo
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: apm-demo
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /HappyPath
        backend:
          serviceName: apm-demo
          servicePort: 80