- name: Make sure machine is updated
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Waiting...
      wait_for_connection:
    - name: Upgrade all packages
      apt:
        name: "*"
        state: latest
        update_cache: true
    - name: Set hostname
      hostname:
        name: "{{ansible_host}}"
    - name: Set /etc/hostname
      copy:
        content: "{{ansible_host}}"
        dest: /etc/hostname

- name: Installs Squid
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Install Squid package
      apt:
        name: "squid"
    - name: Configure squid
      copy:
        content: |
          http_access allow all
          http_port 3128
        dest: /etc/squid/squid.conf
    - name: Restart Squid
      systemd:
        name: squid
        state: restarted
