- name: remove old docker
  become: yes
  yum:
    name:
      - docker
      - docker-client
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: absent
- name: Install required packages
  become: yes
  yum:
    name:
      - device-mapper-persistent-data
      - lvm2
    state: present
- name: Add Docker repo
  become: yes
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    force: yes
- name: Install Docker
  become: yes
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
- name: Create directory
  become: yes
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
- name: Start Docker
  become: yes
  systemd:
    name: docker
    state: restarted
    enabled: yes
    daemon_reload: yes
- name: Create docker group
  become: yes
  group:
    name: docker
    state: present
- name: Add centos user to docker group
  become: yes
  user:
    name: "{{ansible_user}}"
    group: docker