- name: Wait for machines to start
  hosts: all
  gather_facts: no
  tasks:
    - name: Wait for machines to start
      wait_for_connection:

- name: Prepare machines
  hosts: all
  gather_facts: no
  roles:
    - linux
    - docker
    - k8s-base

- name: Enable RPF strict mode (net.ipv4.conf.all.rp_filter=1) - Calico requirement
  hosts: all
  become: yes
  tasks:
    - sysctl:
        name: net.ipv4.conf.all.rp_filter
        value: "1"

- hosts: master
  roles:
    - k8s-master

- hosts: workers
  gather_facts: no
  roles:
    - k8s-worker

- name: Opens kubelet read only port
  hosts: all
  become: yes
  tasks:
    - lineinfile:
        path: /var/lib/kubelet/config.yaml
        line: "readOnlyPort: 10255"
    - systemd:
        name: kubelet
        state: restarted

- name: Set Kubernets kubeconfig on master
  hosts: master
  gather_facts: no
  tasks:
    - shell: kubeadm alpha kubeconfig user --client-name=alex --org=system:masters
      become: yes
      register: kubeconfig
    - file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
    - copy:
        content: "{{ kubeconfig.stdout }}"
        dest: /home/ubuntu/.kube/config
    - copy:
        content: "{{ kubeconfig.stdout }}"
        dest: /Users/alex.fernandes/.kube/config
      delegate_to: localhost
    - shell: kubectl config set clusters.kubernetes.server https://master.k8s.aws.pipsquack.ca:6443
      delegate_to: localhost