- name: Wait for machines to start
  hosts: all
  gather_facts: no
  tasks:
    - name: Waiting...
      wait_for_connection:

- name: Handle prereqs
  hosts: all
  gather_facts: no
  roles:
    - linux
    - docker
    - k8s-base

- name: Kubernetes requirements
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Sets Docker cgroup driver to systemd
      copy:
        content: |
          {
            "exec-opts": ["native.cgroupdriver=systemd"],
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "100m"
            },
            "storage-driver": "overlay2"
          }
        dest: /etc/docker/daemon.json
    - name: Create systemd directory
      file:
        path: /etc/systemd/system/docker.service.d
        state: directory
    - name: Restart Docker
      systemd:
        name: docker
        state: restarted
        daemon_reload: yes

- name: Calico requirements
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Enable RPF strict mode - net.ipv4.conf.all.rp_filter=1
      sysctl:
        name: net.ipv4.conf.all.rp_filter
        value: "1"

- name: Install master
  hosts: master
  roles:
    - k8s-master

- name: Join master
  hosts: workers
  gather_facts: no
  roles:
    - k8s-worker

- name: Opens kubelet read only port
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Adds the option to the config.yaml file
      lineinfile:
        path: /var/lib/kubelet/config.yaml
        line: "readOnlyPort: 10255"
    - name: Restart kubelet
      systemd:
        name: kubelet
        state: restarted

- name: Set Kubernets kubeconfig on master
  hosts: master
  gather_facts: no
  tasks:
    - name: Generates the kubeconfig content
      shell: kubeadm alpha kubeconfig user --client-name=alex --org=system:masters
      become: yes
      register: kubeconfig
    - name: Creates server .kube directory
      file:
        path: /home/ubuntu/.kube
        state: directory
    - name: Create kubeconfig file
      copy:
        content: "{{ kubeconfig.stdout }}"
        dest: /home/ubuntu/.kube/config
    - name: Copy kubeconfig to local machine
      copy:
        content: "{{ kubeconfig.stdout }}"
        dest: /Users/alex.fernandes/.kube/config
      delegate_to: localhost
    - name: Updates the server url to use the public DNS host name
      shell: kubectl config set clusters.kubernetes.server https://master.k8s.aws.pipsquack.ca:6443
      delegate_to: localhost