apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-java
  template:
    metadata:
      name: app-java
      labels:
        app: app-java
    spec:
      containers:
        - name: app-java 
          image: yaalexf/app-java
          imagePullPolicy: Always
          resources:
            requests:
              memory: "384Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_SERVICE_NAME
              value: "app-java"
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_TRACE_ANALYTICS_ENABLED
              value: "true"
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: app-java
  name: app-java
spec:
  selector:
    app: app-java
  ports:
    - port: 8000
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: app-java
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  # host: master.k8s.aws.pipsquack.ca
  - http:
      paths:
      - path: /app-java(/|$)(.*)
        backend:
          serviceName: app-java
          servicePort: 8000
