apiVersion: v1
kind: Pod
metadata:
  name: broken-pod
spec:
  containers:
  - name: good-container
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
  - name: bad-container
    image: busybox2
    command: ['sh', '-c', 'echo Bye Kubernetes! && sleep 3']
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
